name: techkriti20
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_theme: ^1.0.1
  transformer_page_view: ^0.1.6
  eva_icons_flutter: ^2.0.0
  # flare_flutter: ^2.0.1
  # gradient_widgets: ^0.5.2
  # liquid_swipe: ^1.3.1
  url_launcher: ^5.2.4
  # mongo_dart: ^0.4.0
  # custom_navigation_drawer: ^0.0.1
  http: ^0.12.0
  flutter_spinkit: "^4.1.1"
  flutter_html: ^0.8.2
  timeline_list: ^0.0.3
  # firebase_auth: ^0.14.0+5
  snaplist: ^0.1.8
  # flip_panel: ^1.0.1
  # cloud_firestore:
  # flutter_staggered_animations: "^0.1.2"
  hidden_drawer_menu: ^1.1.2
  # flutter_beautiful_popup: ^1.5.0
  # flutter_sticky_header: "^0.4.2"
  # fluro: "^1.5.2"
  # google_maps_flutter:
  # folding_cell: "^0.1.2"
  flutter_svg: ^0.17.2
  webview_flutter: ^0.1.1
  # flutter_webview_plugin: ^0.3.10+1
  # google_nav_bar: ^2.0.0
  # line_icons: ^0.2.0
  # bottom_navy_bar: ^3.0.0
  # flutter_spinkit: "^4.1.1"

  # http:
  # flutter_facebook_login: ^3.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Regular.ttf
        - asset: fonts/Rubik/Rubik-Medium.ttf
        - asset: fonts/Rubik/Rubik-Bold.ttf
        - asset: fonts/Rubik/Rubik-Italic.ttf
          # style: italic

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
    - family: Muli
      fonts:
        - asset: fonts/Muli/static/Muli-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/event/
    - assets/icons/
    - assets/background/
    # - assets/img/
    - assets/images/
    - assets/images/team/
    - assets/images/hospi/
    - assets/images/sponsors/
    - assets/images/sponsors/Black/
    - assets/images/sponsors/Color/
    - assets/images/sponsors/marketing/
    - assets/images/sponsors/Media_Logo/
    - assets/images/sponsors/mnp/Advertisement_Partner/
    - assets/images/sponsors/mnp/Blogger_Outreach_Partner/
    - assets/images/sponsors/mnp/Bollywood_Night_Presented_By/
    - assets/images/sponsors/mnp/Business_Magazine_Partner/
    - assets/images/sponsors/mnp/Career_Development_Partner/
    - assets/images/sponsors/mnp/Digital _artner/
    - assets/images/sponsors/mnp/Digital_Community_Partner/
    - assets/images/sponsors/mnp/Digital_Media_Partner/
    - assets/images/sponsors/mnp/Gold_Sponsor/
    - assets/images/sponsors/mnp/Hindi_Digital_Community_Partner/
    - assets/images/sponsors/mnp/Magazine_Partner/
    - assets/images/sponsors/mnp/News_App_Partner/
    - assets/images/sponsors/mnp/Official_Multiplex_Partner/
    - assets/images/sponsors/mnp/Official_Radio_Partner/
    - assets/images/sponsors/mnp/Online_Hosting_Partner/
    - assets/images/sponsors/mnp/Online_Magazine_Partner/
    - assets/images/sponsors/mnp/Online_Media_Partner/
    - assets/images/sponsors/mnp/Online_Ticket _Partner/
    - assets/images/sponsors/mnp/Opening_Night_Publicized_by/
    - assets/images/sponsors/mnp/Outdoor_Publicity_Partner/
    - assets/images/sponsors/mnp/Print_Media_Partner/
    - assets/images/sponsors/mnp/Prizes_Sponsor/
    - assets/images/sponsors/mnp/Regional_News_Channel_Partner/
    - assets/images/sponsors/mnp/Social_Awareness_Partner/
    - assets/images/sponsors/mnp/Social_Media_Partner/
    - assets/images/sponsors/mnp/Tech_Magazine_Partner/
    - assets/images/sponsors/mnp/Women_Empowerment_Partner/
    - assets/images/sponsors/mnp/Youth_Partner/
    - assets/images/sponsors/White/

    - assets/techkriti_logo.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
